<?php 
$page="company";
include("header.php");
?>
<div id='content'>
	<div id='line_separator'>&nbsp;</div>
	<div id='page_header'>
		<div id='page_navigator'><a href='' class='important'>Condiciones Legales</a></div>
	</div>
	<div class='contentbox'>
		<div class='infobox_info'>
			<h3>Condiciones Legales</h3>
			<p>El contenido de la presente Información Legal, junto con las Condiciones Generales de Venta y Política de Privacidad  tienen por finalidad informar, establecer las condiciones de uso y acceso de los usuarios a las páginas web que figuran bajo los dominios http://www.okycoky.net  y okycoky.net/classics. Las páginas y sus contenidos y marcas son propiedad y están gestionados por ROTELPA, S.A.</p>
<h4>1. DATOS IDENTIFICATIVOS DE ROTELPA, S.A</h4>
<p>ROTELPA es una Sociedad Anónima española, inscrita en el Registro Mercantil de Pontevedra, al Folio 106, Libro 489 de Sociedades, Hoja PO-5657, con CIF A-36641959 y con domicilio social en Parque Tecnológico Logístico, calle C, Nave C-1 (36315), de Vigo (España).</p>
<p>Las páginas web htpp://www.okycoky.net y okycoky.net/classics, son propiedad y están gestionadas por ROTELPA SA. Para cualquier tipo de información, consulta o sugerencia, los Usuarios pueden ponerse en contacto con ROTELPA  a través de la dirección de correo electrónico info@okycoky.com o en el teléfono de Atención al Cliente nº (34) 986 240 001 y, previa cita, en la dirección Parque Tecnológico Logístico, Calle C, Nave C-1, (36315) de Vigo. </p>
<h4>2. CONDICIONES DE USO DE LA PAGINA WEB.</h4>
<p>La utilización de esta página web por parte del usuario se sujeta a las condiciones de uso contenidas en el presente documento y en las Condiciones Generales de Venta y Política de Privacidad, que figuran en los mentados sitios web. El acceso y navegación por las páginas web www.okycoky.net y okycoky.net/classics, y en su caso la compra de cualquier producto presente en la misma, implica que ha conocido, aceptado y consentido sin reservas la información legal, las condiciones generales de venta y la Política de Privacidad, en la versión publicada por ROTELPA en el momento del acceso a la página.</p>
<p>ROTELPA SA puede cambiar en cualquier momento el aspecto de la pagina y las condiciones de uso, asi como los términos y condiciones que estime convenientes y producirán efectos desde el mismo momento de su publicación, por lo que es responsabilidad del Usuario leerlas para conocer su contenido.</p>
<p>El usuario para poder efectuar algún pedido a través de la página web deberá facilitar con carácter previo sus datos personales que le son requeridos a través de un formulario para su registro, siendo responsable de garantizar que la información que ofrezca es cierta, correcta y completa, comprometiéndose a no realizar ningún pedido falso o fraudulento. Al realizar cualquier pedido a través de nuestra página, el cliente declara ser mayor de edad y con capacidad legal para celebrar contratos. El usuario consiente el uso y utilización de la información facilitada a ROTELPA SA conforme a lo establecido en la Política de Privacidad.</p>
<p>El Usuario se compromete utilizar las páginas web www.okycoky.net y okycoky.net/classics de acuerdo con lo establecido en la legislación vigente, únicamente para realizar consultas o pedidos válidos, absteniéndose de utilizar la misma para actividades contrarias a la Ley o usos lesivos de los derechos de terceros, pudiendo en este caso ROTELPA SA, retirar la condición de cliente del sitio web y negarle al acceso a la misma, respondiendo en ese supuesto el usuario de los daños y perjuicios que pudiera ser ocasionados por el citado incumplimiento.</p>
<h4>3. PROTECCION, PRIVACIDAD Y CONFIDENCIALIDAD DE LOS DATOS PERSONALES DE LOS USUARIOS POR PARTE DE ROTELPA, S.A. (POLITICA DE PRIVACIDAD)</h4>
<p>ROTELPA informa que en cumplimiento de lo dispuesto en la Ley Orgánica 15/1999 de 13 de diciembre de Protección de Datos de carácter personal, y el Real Decreto 1720/2007 de 21 de Diciembre, -por el que se aprueba el desarrollo de la Ley Orgánica-, los datos de carácter personal que los Usuarios faciliten a través de la página, serán tratados de manera confidencial y de conformidad con las normas de protección de datos y serán incorporados a ficheros titularidad de ROTELPA, consintiendo expresamente a su recogida y tratamiento y utilización para fines lícitos, que tiene por finalidad la gestión y mantenimiento de nuestros servicios, indispensables para el trámite y envio de pedidos, redacción de facturas, recepción de información y publicidad de productos y servicios de ROTELPA.</p> 
<p>Siendo norma esencial por parte de ROTELPA la seguridad y la garantía y protección de la privacidad de nuestros clientes, es necesario que el Cliente que acceda a la página web para que realizar cualquier pedido que previamente haya leído y aceptado la Política de Privacidad y Protección de Datos aplicable, la cual se puede consultar mediante la activación del link “POLITICA DE PRIVACIDAD”. 
<p>El titular de los datos tendrá en todo momento el derecho de acceso e información, rectificación, cancelación y supresión de sus datos personales, pudiendo hacer uso en cualquier momento de la revocación del consentimiento del Usuario para el tratamiento y cesión de sus datos personales. A tales fines, el usuario podrá modificar o cancelar estos datos, bastará para ello con contactar con ROTELPA, S.A. a través del correo electrónico info@okycoky.com o por correo postal a la Att. Departamento de Atención al Cliente en la Calle C, Nave C-1, 36315, Vigo (España).</p>
<h4>4. PROPIEDAD INTELECTUAL.</h4> 
<p>ROTELPA es titular de todos los derechos de propiedad intelectual o industrial de su página web, asi como de los elementos contenidos en la misma, como son la información de la página, su diseño gráfico y el código. Las marcas OKY ^COKY y OKY´S son también propiedad exclusiva de ROTELPA SA y están protegidas por derechos de autor u otros derechos de protección de la propiedad intelectual.</p>
<p>En virtud de lo dispuesto en la Ley de Propiedad Intelectual, quedan expresamente prohibidas la reproducción, distribución y comunicación pública, incluida su modalidad de puesta a disposición de la totalidad o parte de los contenidos de esta pagina web con fines comerciales en cualquier soporte y por cualquier medio técnico, sin la autorización previa de ROTELPA SA. </p>
<p>El Usuario, se compromete a respetar los derechos de propiedad intelectual o industrial propiedad de ROTELPA SA y deberá utilizar dicho material para su uso personal y privado, únicamente en la forma que sea autorizada  por nosotros o por quienes nos otorgaron licencia para su uso. El usuario deberá abstenerse de suprimir, alterar, eludir o manipular cualquier dispositivo de protección o sistemas de seguridad que estuviera instalado en las páginas web. </p>
<p>Cualquier reproducción o copia, distribución o publicación, de cualquier clase, del contenido de la información publicada en la pagina sin autorización previa y por escrito de ROTELPA  queda prohibido. La autorización para la reproducción puede solicitarse a la dirección de correo electrónico, info@okycoky.com. </p>
<h4>5. EXCLUSION DE GARANTIAS Y RESPONSABILIDAD.</h4>
<p>ROTELPA SA no garantiza la disponibilidad o continuidad del funcionamiento de su página web ni de la ausencia de fallos o interrupciones del servicio, o la ausencia de virus u otros componentes dañinos, por lo que se excluye cualquier responsabilidad por los daños y/o perjuicios de toda naturaleza que puedan deberse a las citadas causas, aunque intentará facilitar, en la medida de sus posibilidades, ayuda técnica a la persona afectada. </p>
<p>La responsabilidad de ROTELPA SA respecto a cualquier producto adquirido en la pagina web, estará limitada exclusivamente al precio de compra de dicho producto. El usuario responderá de los daños y/o perjuicios de cualquier naturaleza que ROTELPA pudiera sufrir como consecuencia del incumplimiento por parte del usuario de la ley o de cualquiera de las normas recogidas en el presente Información Legal o en las condiciones generales de Venta. </p>
<h4>6. CAUSAS DE FUERZA MAYOR.</h4>
<p>No se podrá considerar responsable a ROTELPA SA del incumplimiento del contrato o retraso en el cumplimiento de sus obligaciones en caso de Fuerza mayor,  o provocados por causas externas  fuera de su control como disturbios, huelga total o parcial, especialmente de los servicios postales o de los medios de transporte y comunicación, accidentes o cualquier otro hecho considerado como fuerza mayor por las leyes.</p>
<h4>7. LEGISLACION APLICABLE Y JURISDICCION.</h4>
<p>Estas Normas se rigen por la Ley Española, que será la aplicable en lo no dispuesto en este contrato en materia de interpretación, validez y ejecución. Las presentes condiciones han sido elaboradas de conformidad con lo establecido en la Ley 34/2002, de servicios de la sociedad de la información y comercio electrónico, Ley 7/1998 sobre condiciones Generales de Contratación, la Ley 7/1996 de Comercio Minorista y el R.D.L. 1/2007 de 16 de Noviembre, por le que se aprueba el Texto refundido de la Ley General de Defensa de Consumidores y Usuarios y cuantas disposiciones legales resulten de aplicación.</p>
<p>ROTELPA, S.A. y los Usuarios, para la resolución de cualquier controversia que pudiera surgir, con respecto a su validez, ejecución, cumplimiento o resolución, total o parcial, se someten, con renuncia expresa a su fuero propio o a cualquier otro que, en su caso, pudiera corresponderles, a la competencia de los Juzgados y Tribunales de Vigo (España). </p>
<p>© Copyright 2014. ROTELPA, S.A. Inscrita en el Registro Mercantil de Pontevedra, al Folio 106, Libro 489 de Sociedades, Hoja PO-5657 y con CIF nº A-36641959. Versión 2014-1.</p>

		</div>		
	</div>
</div>
<?php
include("footer.php");
?>